name: pdf_processing
channels:
  - defaults
dependencies:
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - certifi=2022.6.15=py39haa95532_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py39haa95532_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=23.2.0=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - pip:
    - altair==4.2.0
    - attrs==22.1.0
    - blinker==1.5
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - commonmark==0.9.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - idna==3.3
    - importlib-metadata==4.12.0
    - jinja2==3.1.2
    - jsonschema==4.14.0
    - markupsafe==2.1.1
    - numpy==1.23.2
    - packaging==21.3
    - pandas==1.4.3
    - pillow==9.2.0
    - pip==22.2.2
    - protobuf==3.20.1
    - pyarrow==9.0.0
    - pydeck==0.8.0b1
    - pympler==1.0.1
    - pymupdf==1.20.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pytz==2022.2.1
    - pytz-deprecation-shim==0.1.0.post0
    - requests==2.28.1
    - rich==12.5.1
    - semver==2.13.0
    - smmap==5.0.0
    - streamlit==1.12.2
    - toml==0.10.2
    - toolz==0.12.0
    - typing-extensions==4.3.0
    - tzdata==2022.2
    - tzlocal==4.2
    - urllib3==1.26.12
    - validators==0.20.0
    - watchdog==2.1.9
    - zipp==3.8.1